// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5WMG8cB8gfdwVLRPfIzc6iOed90T23Ec',
    appId: '1:495340383811:web:607eda3fbea9401702aef6',
    messagingSenderId: '495340383811',
    projectId: 'fypaapp',
    authDomain: 'fypaapp.firebaseapp.com',
    storageBucket: 'fypaapp.firebasestorage.app',
    measurementId: 'G-41EH4E8RF1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXHwvwPADh9MmDkzvoItSeZwO840--mz4',
    appId: '1:495340383811:android:892475f595ac667c02aef6',
    messagingSenderId: '495340383811',
    projectId: 'fypaapp',
    storageBucket: 'fypaapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcYdT_zcxnukd_CX9mAb9AVRE8DLAurIA',
    appId: '1:495340383811:ios:d3ed4b5b359dd4bc02aef6',
    messagingSenderId: '495340383811',
    projectId: 'fypaapp',
    storageBucket: 'fypaapp.firebasestorage.app',
    iosBundleId: 'com.example.mediVision',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcYdT_zcxnukd_CX9mAb9AVRE8DLAurIA',
    appId: '1:495340383811:ios:d3ed4b5b359dd4bc02aef6',
    messagingSenderId: '495340383811',
    projectId: 'fypaapp',
    storageBucket: 'fypaapp.firebasestorage.app',
    iosBundleId: 'com.example.mediVision',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5WMG8cB8gfdwVLRPfIzc6iOed90T23Ec',
    appId: '1:495340383811:web:fc9c6ae156f3a60802aef6',
    messagingSenderId: '495340383811',
    projectId: 'fypaapp',
    authDomain: 'fypaapp.firebaseapp.com',
    storageBucket: 'fypaapp.firebasestorage.app',
    measurementId: 'G-LDZFJ7FFJV',
  );
}
